apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector
  labels:
    name: nginx-nodeselector
spec:
  containers:
  - name: nginx-nodeselector
    image: nginx:1.19.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  nodeSelector:
    cpu: slow # 指定到标签为cpu=slow 节点上创建pod
