apiVersion: v1
kind: Secret
metadata:
  name: mysecret-app
  namespace: default
type: Opaque
data:
  username: YWRtaW4= # base64 编码后的用户名 admin         echo -n 'admin'| base64
  password: MWYyZDFlMmU2N2Rm # base64 编码后的密码 1f2d1e2e67df
  # Example:
  # password: {{ .Values.password | b64enc }}