apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    name: init-demo
spec:
  containers:
    - name: app-container
      image: busybox:1.28
      command: ["sh", "-c", "echo The app is running! && sleep 3600"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  initContainers: # 先初始按顺序执行启动init容器
    - name: init-db
      image: busybox:1.28
      command: ["sh", "-c", "echo init-db! && sleep 10"]
    - name: init-server
      image: busybox:1.28
      command: ["sh", "-c", "echo init-server! && sleep 10"]
