apiVersion: v1
kind: Namespace
metadata:
  name: ems
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: ems
spec:
  serviceName: mysql # headless 无头服务  保证网络标识符唯一  必须存在
  replicas: 1
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql/mysql-server:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql #自己容器写入数据目录
              name: mysql-volume    #保存到指定一个变量中 变量名字就是 data
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-nfs-pvc
      restartPolicy: Always
  # 下面是直接写在pod.spec.volumeClaimTemplates 中，不需要单独写一个pvc
  # volumeClaimTemplates:  #声明动态创建数据卷模板
  #   - metadata:
  #       name: mysql-volume      # 数据卷变量名称
  #       namespace: ems  # 在哪个命名空间创建数据卷
  #     spec:
  #       accessModes:    # 访问数据卷模式是什么  
  #         - ReadWriteMany
  #       storageClassName: mysql-nfs-sc # 使用哪个 storage class 模板存储数据
  #       resources:
  #         requests:
  #           storage: 2G
  selector:
    matchLabels:
      app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-nfs-pvc
  namespace: ems
  labels:
    app: mysql-nfs-pvc
spec:
  storageClassName: mysql-nfs-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi