apiVersion: apps/v1
kind: Deployment
metadata:
  name:  pc-pvc-deployment
  namespace: default
  labels:
    app:  pc-pvc-deployment
spec:
  selector:
    matchLabels:
      app: pc-pvc-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  pc-pvc-deployment
    spec:
      containers:
      - name:  pc-pvc-deployment
        image:  busybox:latest
        command: ["/bin/sh"] # 每隔1秒循环一次 输出到index.html中
        args: ["-c", "while true; do echo 'Hello NFS!' >> /data/index.html; sleep 1; done"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: nfs-volume
          mountPath: /data # 容器目录
      volumes:
        - name: nfs-volume
          # 申请持久化存储
          persistentVolumeClaim:
            claimName: nfc-pvc
          # nfs:
          #   server: 10.15.0.25 # 远程服务器地址
          #   path: /root/nfs/data # nfs共享路径
      restartPolicy: Always