apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: {{ .Values.namespace }}
  labels:
    app:  nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginx
        image:  {{ .Values.repo }}:{{ .Chart.AppVersion }}
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: nginx
        #       key: DB_HOST
        ports:
        - containerPort:  80
          name:  nginx
      restartPolicy: Always