apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs
  labels:
    app: my-nodejs
spec:
  selector:
    matchLabels:
      app: my-nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nodejs
    spec:
      containers:
        - name: my-nodejs
          image: busybox:latest
          command: ["/bin/sh", "-c", "echo '' ; sleep 3600;"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          secret: # 将secret中配置信息，以文件方式挂载到容器的 /data目录下
            secretName: appliction-nodejs
      restartPolicy: Always
