# 将Secret中配置信息，加载到env 环境变量中
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-env-secret
  labels:
    app: my-env-secret
spec:
  selector:
    matchLabels:
      app: my-env-secret
  replicas: 1
  template:
    metadata:
      labels:
        app: my-env-secret
    spec:
      containers:
        - name: my-env-secret
          image: busybox:latest
          command: ["/bin/sh", "-c", "echo $USERNAME $username $password ; sleep 3600;"]
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret # 去secret中 查找my-secret配置
                  key: username # 在my-secret配置读取 username 的值 赋值给$USERNAME，为linux env环境变量
          envFrom: # envFrom 一次性注入 secret
            - secretRef:
                name: my-secret
      restartPolicy: Always
