apiVersion: apps/v1
kind: Deployment # controller 控制器类型
metadata:
  name: nginx-deployment # Deployment控制器名称
  namespace: default # 使用默认命名空间
  labels: # Deployment
    app: nginx-deployment
spec:
  selector: # 选择哪些标签带有app=nginx的pod进行控制
    matchLabels:
      app: nginx # 这里标签与template中labels所对应
  replicas: 3 # 创建副本数
  template: # 控制器所管理pod的配置信息
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.4
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env: # 环境变量
            - name: NG_HOST
              value: 1.1.1.1
          ports:
            - containerPort: 80
              name: nginx
      restartPolicy: Always
